### ISSUE TITLE
Update JSZip

### ISSUE THREAD

**Issue by dduponchel** [jsantell/node-zip-dir#1]
The commit b77c0aa7a1 removed the npm dependency to JSZip and added the sources of the v2.0.0, to work with node v0.8.
JSZip is now in version 2.4.0 and can be used with `require()` directly (among other improvements). The tests of JSZip pass on nodejs v0.8 but I'm interested in any other bug you can find :)
I highly suspect the `vm.createContext()` in jszip/index.js to break things on windows in iojs (a nodejs fork) : see mozilla/jpm#243 and Stuk/jszip#197. I fixed the error when I upgraded the JSZip version of this module.

**Comment by jsantell** [comment]
good eye, thanks!

**Comment by jsantell** [comment]
Fix in v1.0.0
