### ISSUE TITLE
When there are too many opened files, their size is 0 in the zip

### ISSUE THREAD

**Issue by laurentj** [jsantell/node-zip-dir#4]
On Linux at least, when we want to zip hundred files, some of them are empty in the resulting zip archive.

It seems that is because zip-dir opens too many files at the same time, and then reaches the limit of opened files of the O.S. When the limit is reached, files cannot be read.

See the issue  mozilla-jetpack/jpm#460  for details

**Comment by laurentj** [comment]
Fixed by PR #5

**Comment by kumar303** [comment]
I'll cut a release for this soon

**Comment by petervdn** [comment]
has this been patched? i'm having the exact same issue

**Comment by jsantell** [comment]
Both 1.0.1 and 1.0.2 should have the [fix in question](https://github.com/jsantell/node-zip-dir/commit/413ec340a83ae68cba05349d6d8da82d6652d499)
