### ISSUE TITLE
Infinite loop & 100% CPU utilization

### ISSUE THREAD

**Issue by laurentj** [jsantell/node-zip-dir#6]
PR #5 introduced an issue when we want to zip thousand files.

In fact, when the readed files count has reached the limit maxOpenFiles in addItem(), the addItem() function is called itself. And it is called recursively until some files have been read. But if reading files takes much more time than listing all files, we reach a point where there are too many infinite recursive loops for many files. Then it takes so many CPU resources that there are not enough CPU resources to read files. And the program never ends.

**Comment by kumar303** [comment]
Hmm, I guess we need a proper queue to solve the max-open-files issue after all. Maybe switching to [async.queue()](http://stackoverflow.com/questions/9539886/limiting-asynchronous-calls-in-node-js) would be easy enough.

**Comment by kumar303** [comment]
@kiboke could you try re-doing your patch using `async.queue()` as described above? ^

Docs: https://github.com/caolan/async#queue
